name: Codecov

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test drupal-jsonapi-params
    steps:
    - uses: actions/checkout@v3
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8
    - name: Install requirements
      run: pnpm install
    - name: Run tests and collect coverage
      run: pnpm run test
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v2
